### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#1]
# Introduction

The current load on the Svelte OSS maintainers is currently high with many issues and pull requests open spanning across many repositories. While Svelte usage is increasing around the world so does the need to handle support and questions, in addition to the bugs that inevitably are discovered. Svelte Society aims to off-load as much of the support load as possible by building a website containing information such as tutorials, guides and cookbooks.

# Overview

To understand the project and it&#39;s moving parts this document aims to give an overview as well as general development direction. The system will consist of two parts, a front-end built in Svelte and a back-end built in Elixir &amp; Phoenix.

The specific technologies and solutions we end up using can be discussed in their respective issues that will be created in this repository shortly.

## Front-end

The actual UI and UX of the site shall follow as close as possible the current [Svelte Society website](https://sveltesociety.dev). A [Figma](https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website) document exists but is currently only made for the Svelte Society Day but can hopefully be expanded to encompass components that will be needed.

The general technology needs to support some form of static site generation as the site will be entirely static. I suggest handling this using Routify for routing. Data fetching needs to be done at build time to fetch the list of Packages. Markdown should be used on the cookbook recipe pages.

The front-end needs to contain these parts:

Phase 1:
- Cookbook (recipes of varying length that shows the user how to implement different things)
- Packages (a list of NPM packages that are relevant to Svelte users; Components, Libraries, etc.)
- Submission Page (this should pretty much send a POST to the back-end with details of the package or cookbook that someone wants to submit)

Phase 2
- Meetup Page (contains list of meetups around the world with links to)
- Adding MDSveX support to Cookbook pages (improves functionality and clarity, and also makes it possible to easily take advantage of the official REPL component)

## Back-end
As mentioned, the back-end is made in Elixir &amp; Phoenix. Even though there will be a small user (admins, moderators, etc.) facing part it is minor, thus the priority is on functionality rather than visuals. That being said, the design language of the front-end will be used as much as possible.

It will handle the storage of the lists of packages and cookbook recipes as well as everything else that is database related. A key functionality of this part of the project is to handle moderation and administration of the Cookbook and Packages part of the front-end.

Like the front-end there are a couple of key things that need to be there:

Phase 1
- Data API (used to deliver data to the front-end)
- Authentication System (restrict access to front facing part of the back-end)
- Queue System (handles approval and editing of submissions)
- Recipe Creator (possibility for users to submit and create recipes)

Phase 2
- Add support for MDSveX (improves cookbook recipe experience)
- Meetup Handling System

# Milestones

1. Phase 1 (May 17th)
 This is pretty much the date we launch the website.
1. Phase 2 (TBD)
 Improves site functionality and user experience.

**Comment by sw-yx** [comment]
nice

**Comment by Wolfr** [comment]
Great! I love that you put out a clear vision.

**Comment by sw-yx** [comment]
is there a particular reason you picked may 17 launch date? :)

**Comment by kevmodrome** [comment]
Nope! Entirely arbitrary haha! Seemed like a good amount of time after the online meetup. You think it's too much? Too little? I'm open moving it

**Comment by Wolfr** [comment]
Seems like too soon, building a site needs more prep than a few weeks.

**Comment by sw-yx** [comment]
launch early, launch often :)

**Comment by kevmodrome** [comment]
We can always revise if we're nowhere near a workable site at that point in time :)

**Comment by kevmodrome** [comment]
Closing because stale and not up-to-date at all. Will write a new one at some point 🙈

**Comment by sw-yx** [comment]
ty

**Comment by UnevenCoder** [comment]
Can I know more on how the ui has to be made the goal
