### ISSUE TITLE
MadeWithSvelte integration

### ISSUE THREAD

**Issue by sw-yx** [svelte-society/sveltesociety.dev#10]
had some chats with https://madewithsvelte.com/ (https://twitter.com/arminulrich and https://twitter.com/_feloidea)

they are doing a better job than us of tracking svelte projects for showcase. they have an api endpoint and we can show random svelte projects from their list

**Comment by kevmodrome** [comment]
Sounds like a good idea!

**Comment by Wolfr** [comment]
They do seem commercially incentivized. But if it helps to have better content sooner...

**Comment by arminulrich** [comment]
Heya!

happy that you think we do a good job - working hard on curating all the awesome dev resources daily :)

we expose a single endpoint to get 10 random posts: https://madewithsvelte.com/api/v1/posts/random

btw I added the SvelteSociety Logo to https://madewithsvelte.com if we can do anything else let me know :)

**Comment by arminulrich** [comment]
@Wolfr this is _kinda_ true - 99% of our work is free, across all platforms; but we do offer to skip the submission queue by supporting/paying us - if this is against what you want here I totally understand!

**Comment by kevmodrome** [comment]
> They do seem commercially incentivized. But if it helps to have better content sooner...

This is true, we might want to make sure we decide on some framework to handle things like this correctly. I'll make an issue.

**Comment by Wolfr** [comment]
I think there is definitely room for commercial entities within OSS, like @kevmodrome says we just need to talk about it and come up with a reasoning and sort of “policy”.

At this stage I also don't want to make a big deal out of it and don't want it to be a blocker.

One example I can think of from the top of my Vue.js docs promoting https://vueschool.io/ .

**Comment by sw-yx** [comment]
i'm ok with it :)

**Comment by sw-yx** [comment]
definitely still keen on pulling data from MWS, i love how they surface good stuff

**Comment by HAUDRAUFHAUN** [comment]
I think this could be something that we make on a new design index page. Maybe like [svelte.dev](https://svelte.dev)
