### ISSUE TITLE
Padding in CategoryTree

### ISSUE THREAD

**Issue by stephane-vanraes** [svelte-society/sveltesociety.dev#102]
![image](https://user-images.githubusercontent.com/13446670/132224818-e52bbbbe-45d0-452d-b722-a5e40f484bc8.png)
![image](https://user-images.githubusercontent.com/13446670/132224854-a052e3cb-5753-40cc-914b-961a6acf0da7.png)

In both cases some extra margin in the top can be good

Both use the component `CategoryTree` which has `margin: 0 0 0 1.75rem;`

I suspect a top margin of 1rem should add sufficient white space

**Comment by rahulshawdev** [comment]
Can I work on it??

**Comment by dustinjray** [comment]
I can handle adding the 1rem of white space.
