### ISSUE TITLE
feature: event section

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [svelte-society/sveltesociety.dev#103]
In the description of this repo stands that the website includes information about events. Would it make sence to build a section for the previous and the future events? I would imagine that like the [component page](https://sveltesociety.dev/components) but for events/meetups.

**Comment by kevmodrome** [comment]
Sounds like a cool idea! I'd make it more "listy" though, rather than big cards for each event. You're welcome to give it a try :)

**Comment by HAUDRAUFHAUN** [comment]
Ok I'll try to work on it

**Comment by kevmodrome** [comment]
Thanks for the help on this!
