### ISSUE TITLE
"Sign up" button on Recipes page does nothing

### ISSUE THREAD

**Issue by geoffrich** [svelte-society/sveltesociety.dev#108]
The "Sign up" button on the [Recipes page](https://sveltesociety.dev/recipes) currently does nothing. Is there an existing page this should link to?

![image](https://user-images.githubusercontent.com/4992896/104505861-69e67400-5599-11eb-8428-99aaaa5b524c.png)

**Comment by sw-yx** [comment]
no not that I know of - we should probably change "sign up" to "file an issue" on this repo

**Comment by HAUDRAUFHAUN** [comment]
I will have this issue resolved in my next PR

**Comment by HAUDRAUFHAUN** [comment]
![Screenshot_2021-01-16  Recipes - Svelte Society(1)](https://user-images.githubusercontent.com/47633893/104811745-fd1fe380-57fd-11eb-97e8-e4d93dc82a02.png)

Now it looks like this. The "Button" is an anker element the links directly to [https://github.com/svelte-society/sveltesociety.dev/issues/new](https://github.com/svelte-society/sveltesociety.dev/issues/new)

**Comment by HAUDRAUFHAUN** [comment]
Issue resolved with #113. I close it.
