### ISSUE TITLE
Links to society

### ISSUE THREAD

**Issue by stephane-vanraes** [svelte-society/sveltesociety.dev#109]
Spread the word and build communities!

The svelte society site should list links to societies wordwide so we can encourage community building. Adding new entries should be easy, so perhaps it can be build from a json file ? 
```json
[{
  "name": "Svelte Society Antartica",
  "twitter": "@pngwn",
  "url": "svelte-society.ant"
}]
```

Questions:

Where to feature ? 
Can we make this prominent on the frontpage ? "Looking for a Svelte Community near you ?"
Add some text on how to get your community listed.

Required:

some copy (I am horrible at writing short stuff)
links/handles

**Comment by HAUDRAUFHAUN** [comment]
I will try to find a solution for it 😃

**Comment by HAUDRAUFHAUN** [comment]
![Screenshot_2021-01-15  Events - Svelte Society](https://user-images.githubusercontent.com/47633893/104763704-9a2f3d80-5766-11eb-9d03-3f58b9fc7482.png)

Here you get a preview of my solution. What dow you think about it?
The data Model for the societys actual looks like:
```json
[{
    "name": "London Svelte Meetup",
    "country": "🇬🇧 Great Britain",
    "url": "https://www.meetup.com/svelte/"
  },
  {
    "name": "Svelte Dublin",
    "country": "🇮🇪 Ireland",
    "url": "https://www.downtomeet.com/Svelte-Dublin"
  },
  {
    "name": "Svelte Society Stockholm",
    "country": "🇸🇪 Sweden",
    "url": "https://www.downtomeet.com/Svelte-Society-Stockholm"
  }
]
```
but i think its expandable with thinks like organisators of the communities f.e.

**Comment by sw-yx** [comment]
this looks really good!

**Comment by HAUDRAUFHAUN** [comment]
yes this could be a nice feture @sw-yx

**Comment by kevmodrome** [comment]
I'll close this, thanks for the PR!
