### ISSUE TITLE
How do we deal with commercial entities?

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#11]
This just came up in the issue about madewithsvelte.com. I have nothing against having it on the site at this moment but I do think we need to make sure we handle this correctly. Let's explore how other projects like these handle this.

**Comment by kevmodrome** [comment]
In accordance with the design I did for the recipes page I think there is room to allow for companies/individuals to in the long run maintain some of the Recipes in exchange for a short blurb beneath them. Not sure if that's a good idea though, would be nice with some opinions on this. 

What does the Svelte project have to say about things like these? Ping @antony. Maybe you already know the answer, if not, could you check with the rest of the maintainers?

**Comment by sw-yx** [comment]
ya i'm fine with that. more maintainers the better. but we'll say that our decision is final when conflicts arise.

**Comment by sw-yx** [comment]
let's reopen this when necessary.
