### ISSUE TITLE
Svelte Society '20 page - post-event on site

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/sveltesociety.dev#12]
I think it would be nice if we do a post event version of the Svelte Society Day website.

The way I envision it is that it becomes a page on the website where we remove the FAQ, where we add a text about what went down on April 26th, and change the block of 10 speakers to a block that links out to youtube to their talk.

Here is a beginning of the copy:

> On April we 26th 2020 the Svelte community gathered for an online event about Svelte. Together we watched ten talks, chatted about them, learned a thing or two and got to know the community! On this page you can find a link to all the talks from that day.

https://www.figma.com/file/iCHWpdoox2Ls3NnfujVdMz/Svelte-Society?node-id=10%3A291

Feel free to pick this up from the design file, either by designing or helping with dev. I am stopping work for today on this.

**Comment by kevmodrome** [comment]
That's a good idea. I will try to get to it during the weekend if I have time, if someone wants to get to it before that you're free to open a PR.

**Comment by Wolfr** [comment]
Overall I would love to help with the site's code as well but this might also be more like a weekend thing.

**Comment by sw-yx** [comment]
this is done
