### ISSUE TITLE
Staging Information - Preview Site URL

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#12]
Staging site can be viewed here: https://staging.sveltesociety-2021-dqq.pages.dev

**Comment by swyxio** [comment]
@kevmodrome does cloudflare have a github app that auto adds these previews per PR, can you install it?

**Comment by kevmodrome** [comment]
No, I'll add a Netlify integration as well

**Comment by kevmodrome** [comment]
Why did you close this @benmccann ?

**Comment by benmccann** [comment]
Ah, sorry. I didn't realize we were still using the staging site now that things are live at sveltesociety.dev. I figured we'd just be deploying directly there now. The staging URL was pointing to old code for me. Any reason to keep staging since we have Netlify previews on all the PRs?

**Comment by kevmodrome** [comment]
I guess it's not necessarily needed, i just like the idea of staging -> master as an extra step to make sure it works - I did notice the URL was wrong, updated it with the correct one

**Comment by brittneypostma** [comment]
~~URL isn't loading for me, I can't see the staging site live without a deploy preview.~~

I said this and then I tried again and it worked...don't mind me.

**Comment by MacFJA** [comment]
@benmccann You remove the branch `staging` with this PR #400 

Was it intentional ?

**Comment by benmccann** [comment]
Yes, it was such a headache to constantly deal with the extra step
