### ISSUE TITLE
Remove use of `$page.query`

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#123]
@ABarnob looks like I was wrong in https://github.com/svelte-society/sveltesociety.dev/pull/108 that it was a SvelteKit bug and it was really a bug in the implementation, so maybe I shouldn't have merged it yet (more details available in the issues linked to from https://github.com/sveltejs/kit/issues/2444#issuecomment-921092592). Do you think you could fix it?

We'd either need to not prerender the page (e.g. switch from `adapter-static` to `adapter-netlify`) or update the dropdown in `onMount` using `location.search`). The latter seems potentially safer because it's a code change only and doesn't involve the possibility of needing to make any hosting changes, but @kevmodrome could weigh in if he feels differently

**Comment by aantusahaa** [comment]
I've read through corresponding issues. But I'm not entirely sure about the specific reason behind not being able to use $page.query with pre-rendered pages. Would you please explain it to me?

**Comment by benmccann** [comment]
A pre-rendered page is one that gets rendered and saved to HTML during build-time. The query could be anything at runtime. Thus, you can't precompute the page contents at build-time based off what the query is because we don't know yet since its value could change.

**Comment by aantusahaa** [comment]
Ah! Right. Thanks for clarifying @benmccann
