### ISSUE TITLE
Inconsistent Naming for Titles

### ISSUE THREAD

**Issue by brittneypostma** [svelte-society/sveltesociety.dev#127]
The metatags store has a title property that is being used in the routes inconsistently. It would be nice if we could pick one convention throughout. Probably `{title}-Svelte Society` or `{title}|Svelte Society` would work well. Have the title be dynamic for the routes to set and the other part be there all the time.

**Comment by benmccann** [comment]
Sounds like a good idea to me. I would put a space on either side of the `-` or `|`

**Comment by kevmodrome** [comment]
Agreed, personally I like "Title - Svelte Society"
