### ISSUE TITLE
Recipes Icons

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [svelte-society/sveltesociety.dev#136]
At the recipe index the Icons seem all to be one single instead of customs for each categorie like a docker icon for the hosting section. So it could be nice 

- [x] if we would use the icon component instead of a svg file
- [x] if we add a prop to the icon component to control the size

I could work on this but first I wanted to get feedback about this idea.

**Comment by kevmodrome** [comment]
TThis sounds like a good idea! I would take a look at Amelia Wattenbergers icon component for inspiration: https://svelte.recipes/components/icon

**Comment by HAUDRAUFHAUN** [comment]
Resolved by #140.
