### ISSUE TITLE
Call for ideas for a sleek design for cheatsheet page

### ISSUE THREAD

**Issue by peopledrivemecrazy** [svelte-society/sveltesociety.dev#139]
I was discussing with my friend if there was a way to improve the page he came up with this

![image](https://user-images.githubusercontent.com/3922469/105458963-75c7e980-5caf-11eb-8d15-0b70f3342f95.png)

A search bar too could be a great addition to navigation I can recommend this https://github.com/roxiness/poindexter

The original design is at #4

**Comment by HAUDRAUFHAUN** [comment]
I would to a crossover between the actual and this design (I would still use the mac-like three circles in the corner)

**Comment by Isaac-Tait** [comment]
I second the mac like circles. I would make the card height dependent on content instead of uniform height - the dead space at the bottom looks a little off to me. Overall though I think Svelte Brasil did a solid job on it...

**Comment by HAUDRAUFHAUN** [comment]
I don't know if this is a good idea, but I just wanted to share it with you to get feedback. I used blue for the header, because then the mac buttons have a better readability:
![Bildschirmfoto 2021-01-27 um 17 50 43](https://user-images.githubusercontent.com/47633893/106024675-4c042d80-60c8-11eb-8661-932e99efe3c5.png)

**Comment by peopledrivemecrazy** [comment]
Did you use `var(--color-secondary)` it is easier on the eyes tho.

**Comment by HAUDRAUFHAUN** [comment]
Ok, thank you for the hind, now I use that.

**Comment by Isaac-Tait** [comment]
The blue does pop rather nicely on the screen. 💯

**Comment by HAUDRAUFHAUN** [comment]
What is with making the single 'windows' hidable with clicking on the mac-dots? Should I implement this also?

**Comment by peopledrivemecrazy** [comment]
We can do this on the next incremental update; also we could work on something like [this (discord chat)](https://discord.com/channels/457912077277855764/728292755087818924/802077163784241182).

**Comment by Demysdcl** [comment]
> I don't know if this is a good idea, but I just wanted to share it with you to get feedback. I used blue for the header, because then the mac buttons have a better readability:
> ![Screenshot_2021-01-27 Cheatsheet - Svelte Society](https://user-images.githubusercontent.com/47633893/106028933-d8b0ea80-60cc-11eb-8746-dda774ec8bd2.png)

I updated the Svelte Brasil site with this sugestion:

https://sveltebrasil.dev/#/cheatsheet

**Comment by kevmodrome** [comment]
Closing since this was implemented and merged :)
