### ISSUE TITLE
Possible integrations with... integrations

### ISSUE THREAD

**Issue by antony** [svelte-society/sveltesociety.dev#15]
Note that I've just started merging some PRs in this repo. https://github.com/sveltejs/integrations

It would be good to think about

- [ ] is it a data-source, source of truth, or otherwise?
- [ ] Do we want to use it in-situ, adopt it, make it indexable?

among other things.

**Comment by sw-yx** [comment]
i have no idea at all 😅 never used that repo

**Comment by kevmodrome** [comment]
I could see this living on the site. Seems to be closely related to what we're doing here at least. Could either use it as a SoT and move it over once the back-end is ready.

**Comment by sw-yx** [comment]
thoughts?

**Comment by sw-yx** [comment]
i reckon we let this slide for now, not a high priority in my mind.
