### ISSUE TITLE
Add note for Sapper being unmaintained in Template section

### ISSUE THREAD

**Issue by maxcell** [svelte-society/sveltesociety.dev#150]
Howdy folks!

I noticed in the [Svelte discord](https://discord.com/channels/457912077277855764/473466028106579978/898223577625665586) it was raised that Sapper is no longer being maintained. Do we want to consider adding a note about that [similar to the Sapper README](https://github.com/sveltejs/sapper#sveltekit)?

**Comment by benmccann** [comment]
Where on the site would we put it?

Are there other places around the Svelte web properties we could put it that would have let you realize this sooner?

**Comment by maxcell** [comment]
From my own research, the other web properties for Svelte don't mention Sapper except for one book between it and just Svelte. In fact, I didn't know about it till I looked at the [Templates section of this site](https://sveltesociety.dev/templates#sapper) of the Svelte Society when I was looking for examples.
