### ISSUE TITLE
Recipe request: dynamically importing a Svelte component

### ISSUE THREAD

**Issue by sw-yx** [svelte-society/sveltesociety.dev#150]
based on @higsch's request: https://twitter.com/h_i_g_s_c_h/status/1353809757602197506

i think it is a mix of:

- svelte component template: https://github.com/sveltejs/component-template
- `svelte:component`: https://svelte.dev/tutorial/svelte-component

but am also wondering if the default webpack/rollup loaders would already handle this seamlessly. not sure

**Comment by higsch** [comment]
I think it is the way @Rich-Harris is importing and embedding components at the NY Times.
```
window.NYTG.load = function (module) {
  var url = new URL(module, location.href).href;
  return eval("import('" + url + "')");
};

Promise.all([
  NYTG.fetch(
    'https://static01.nyt.com/newsgraphics/2020/03/16/coronavirus-maps/d4b63b1513c5d5f9b232475a9b6ce5a2b255ebc6/data/navigation_links.json'
  ),
]).then(function (data) {
  var target = document.querySelector('[data-component="2"]');
  var url = NYTG.VIRUS_ASSETS + '/build/js/breadcrumbs.js';
  var props = { navigation: data[0] };

  let component;

  NYTG.load(url).then((mod) => {
    const Component = mod.default;

    component = new Component({
      target,
      hydrate: true,
      props,
    });
  });
});
```
But I have no idea how I would need to compile my component to be working with this pattern.

**Comment by higsch** [comment]
Oh, I think it works with `index.mjs` from https://github.com/sveltejs/component-template.

**Comment by sw-yx** [comment]
@higsch i saw from twitter that you managed to solve it right? do you think it's worth writing up a solution? til now i'm not 100% sure what your requirements were heheh

**Comment by higsch** [comment]
Yep, I solved it. It has simply been taking the `index.mjs` instead of the `index.js` from the compiled component template. I used it for a project which will be published soon, then I can link this here.
