### ISSUE TITLE
Recipes: Use docker-compose

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [svelte-society/sveltesociety.dev#156]
I want to get feedback about the idea writing a recipe about how you can use docker-compose with your svelte project, maybe already for development so that it's easier to get started if you want to use database systems e.g. with your svelte application.

**Comment by sw-yx** [comment]
i think it'd be nice but also not a very high priority since docker is at quite a different layer. looks like we have https://sveltesociety.dev/recipes/publishing-and-deploying now anyway
