### ISSUE TITLE
Update stars workflow isn't running yet

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [svelte-society/sveltesociety.dev#159]
I just want to report that the workflow from #146 isn't running on the repo yet...

**Comment by mikeesto** [comment]
It's not in the master branch yet, should be picked up as a workflow once it lands

**Comment by mikeesto** [comment]
Well the action ran today but wasn't able to commit the changed json file as "at least 1 approving review is required by reviewers with write access". Heavily discussed here and unfortunately not an easy fix: https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/35Bit . 

One potential solution is to create an "admin" user that has admin writes to the protected branch (i.e. can push without an approving review).

**Comment by MacFJA** [comment]
Should we commit to this repo every time the workflow is run ?
It's like spamming the git history 🤔 
Don't we risk to have conflict with new components additions ?

Maybe the stars list should be in a not committed file ?
