### ISSUE TITLE
Community blog posts

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/sveltesociety.dev#16]
Since my [PR for a blog post about community](https://github.com/sveltejs/svelte/pull/4763) is stuck in PR-land (and has been for over a month now if you count the [v1](https://github.com/sveltejs/svelte/pull/4645)) I think I want to just publish content somewhere else.

It doesn't make sense to me to have an outdated blog on Svelte.dev. I tried to fix it, but I can't get it moving.

After the Svelte Society Day it was pointed out that other coding communities have multiple “unofficial” sites where the community can do it's thing.

One such example is [Ember](https://emberjs.com/) linking out to community efforts from their main menu.

As much as I'd love to have a bit of activity on the main Svelte site, rather than give up I would go for an alternative: blog on the Svelte Society site. If we prove ourselves to be a nice community resource, maybe we can get a main menu link from the Svelte site 😉 ?

Would anyone else be interested in writing? If we get the site up with a cookbook section for which @sw-yx already created amazing content, a blog, links to SS day videos (#12) etc. it could be a great resource for people looking beyond the official docs.

**Comment by kevmodrome** [comment]
I'm open to setting up a blog on the svelte society website, go for it! I don't really have time at the moment to set it up but it shouldn't be too much work to add MDSveX or some other MD thing to it.

**Comment by sw-yx** [comment]
we have a more active blog on svelte.dev thanks to @d3sandoval, so now perhaps less necessary?
