### ISSUE TITLE
Recipes: Data fetching // Graphql queries

### ISSUE THREAD

**Issue by HAUDRAUFHAUN** [svelte-society/sveltesociety.dev#178]
I just wanted to ask if it would make sense to add a recipe or cheatsheet card about datafetching or using svelte with grapqhl.

**Comment by HAUDRAUFHAUN** [comment]
I've seen that data fetching is already there, when I have time I will add a guide for graphql too.

**Comment by sw-yx** [comment]
thanks Haudraf, sorry i didnt respond till now haha
