### ISSUE TITLE
Add official SvelteKit Adapter

### ISSUE THREAD

**Issue by MacFJA** [svelte-society/sveltesociety.dev#185]
I see that the **Components** pages don't have SvelteKit official Adapter

**Comment by brettearle** [comment]
Hello, first timer here. Wondering if I could give this a go?

**Comment by MacFJA** [comment]
> Hello, first timer here. Wondering if I could give this a go?

Of course !
Feel free to pick this task.

**Comment by brettearle** [comment]
You looking for specific adapter or just the auto adapter?

**Comment by MacFJA** [comment]
For all adpater: https://github.com/sveltejs/kit/tree/master/packages

- [adapter-auto](https://github.com/sveltejs/kit/tree/master/packages/adapter-auto)
- [adapter-cloudflare-workers](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare-workers)
- [adapter-cloudflare](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare)
- [adapter-netlify](https://github.com/sveltejs/kit/tree/master/packages/adapter-netlify)
- [adapter-node](https://github.com/sveltejs/kit/tree/master/packages/adapter-node)
- [adapter-static](https://github.com/sveltejs/kit/tree/master/packages/adapter-static)
- [adapter-vercel](https://github.com/sveltejs/kit/tree/master/packages/adapter-vercel)

**Comment by brettearle** [comment]
Awesome, will get to. 👍

**Comment by brettearle** [comment]
pull request submitted

added official sveltekit adapters to components.json #276

**Comment by MacFJA** [comment]
Thanks !
