### ISSUE TITLE
Debounce on text input

### ISSUE THREAD

**Issue by frederikhors** [svelte-society/sveltesociety.dev#190]
For the first time only today I noticed that an efficient example of debounce on text input is missing.

Is there anyone who can write a good example in recipes?

**Comment by kevmodrome** [comment]
Not sure it makes sense as a specific recipe, maybe a longer form article on different ways of doing debuncing? In-component, action, store, etc?

**Comment by frederikhors** [comment]
@kevmodrome.

I found some here: https://github.com/sveltejs/svelte/issues/884.

**Comment by MacFJA** [comment]
Also, not a long ago **lihautan** release a video about High Order Store, [one of them is a debouce](https://youtu.be/p1aPfVyZ1IY?t=235)
