### ISSUE TITLE
Injecting a Svelte component into an existing site

### ISSUE THREAD

**Issue by antony** [svelte-society/sveltesociety.dev#192]
Grabbing this from https://github.com/sveltejs/svelte/issues/4783

I'll open a PR shortly or maybe @lingtalfi wants to. I appear to have asked for corrections and closed the issue on Svelte, and then never followed up, so please accept my apologies!

**Comment by mithrendal** [comment]
thanks @antony for opening this issue. 

The background here: when having to develop new stuff to an quite large existing legacy webapp, and you want to use svelte to do that. E.g. integrating svelte dialogs or components into that existing app, whats the proper way to do it?
 
I tried the recipe of @lingtalfi ... although it works fine and answers this issues title, it does so only for "flat" svelte components. In case you have nested svelte components, the recipe is not working ... 

So the question is 

### **how to integrate "_non-flat_" svelte components** ?

**Comment by alexgagnon** [comment]
I can confirm that local nested Svelte components work, however I'm having a hard time referencing one from the another package and not use globals/externals (i.e. I want to include the code for that component). For example, I have a local component library (examples.svelte), and I'm trying to include one in another project that I'd like to inject. This could be my limited knowledge of Rollup or something, but no matter my rollup config, it always adds a reference to the library, and then the browser fails to find it. I can try to provide a sample repo....
