### ISSUE TITLE
tech: front-end

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#2]
I'm opening this to discuss different technologies we can use to build the front-end. All suggestions are welcome and the choices are not set in stone. I will be focusing on the back-end part of this project mostly so for me it's not that important what technologies we use.

I know @sw-yx is keen to use SSG, if that's not an option, or he wants to build a new version, I would personally suggest [Routify](https://routify.dev/) as a starting place. It's a great router that I've had the pleasure of implementing recently on a bigger SPA-style project. Jake is very quick to help  in the Routify discord if something is not working. It has good SSR support and is generally very nice to work with.

For the Svelte Society Day website I built recently I used a project called [MVP.css](https://andybrewer.github.io/mvp/). It's pretty much gives great out of the box styling and works well with Svelte's scoped styling.

What other stuff do we need to take into consideration here?

**Comment by sw-yx** [comment]
we absolutely dont have to use SSG at all :)

**Comment by antony** [comment]
I don't know what SSG is :) Anyone?
Routify is also fine, if SSG isn't on the table.

I'm not into CSS frameworks at all, since I just constantly get burned with them, but if MVP gives some sensible defaults and we don't plan to override them constantly, then that sounds like a good solution.

Probably you need to decide:
* SCSS/Stylus or not
* Component libs - if there are plans/requirements for any.

**Comment by kevmodrome** [comment]
I'll let the repository speak for itself: [SSG](https://github.com/sw-yx/ssg)

I generally don't like them either. MVP gives you some nice [barebones](https://github.com/svelte-society/svelte-society-day-2020/blob/master/static/global.css) styling with sane defaults and css variables from the get-go. And this stylesheet just happens to already be set up with the correct colors and stuff that we need. I find it to work very well with Svelte and the "API" surface is pretty much nil. It's all HTML tags and combinations of them.

**Comment by sw-yx** [comment]
just set up the basic layout @kevmodrome  i can help to fill out content

**Comment by kevmodrome** [comment]
All right, i'll set something up later today! :) It won't be fully responsive to all screen sizes yet though.
