### ISSUE TITLE
Gitpod-schema no content with colon is missed

### ISSUE THREAD

**Issue by Scouterdev** [svelte-society/sveltesociety.dev#20]
```
Unable to load schema from 'https://gitpod.io/schemas/gitpod-schema.json': No content.
can not read an implicit mapping pair; a colon is missed
```

For gitpod.yml file have problem message..

Screenshot: gitpod for error
https://scrnli.com/VWP7x9CWrPmq3n

**Comment by kevmodrome** [comment]
Maybe @mikenikles can help with this?

**Comment by mikenikles** [comment]
I opened a PR to address that. Interestingly enough, fixing the indentation of `pnpm dev` wasn't enough initially, I ended up deleting the file and pasting the content back in.

My suspicion (although I can't proof it 😄) is that there was a whitespace issue somewhere in the file. Maybe also just some other glitch, but the #21 PR fixes it.
