### ISSUE TITLE
feature: Components Index Page

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#21]
The [components](https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=196%3A102) page needs to be implemented according to the design.

Since the functionality is not 100% set in stone yet it would be a good idea to not focus on the actual inner-workings of for example the filter part. Focus on the design! 👍

**Comment by cstrnt** [comment]
I’m gonna start working on that tomorrow :)

**Comment by kevmodrome** [comment]
@cstrnt did you managed to get started on this?

**Comment by cstrnt** [comment]
@kevmodrome yes, I got quite some stuff done already. Right now im trying to make it look polished. Might be able to finish it tonight

**Comment by kevmodrome** [comment]
This one also has mobile designs now: https://cln.sh/elJxc6

**Comment by UnevenCoder** [comment]
media queries width ?

**Comment by kevmodrome** [comment]
Use grid-template-columns, no need for media queries

**Comment by UnevenCoder** [comment]
doing it

**Comment by kevmodrome** [comment]
The buttons need to be adjusted so that they take either full or half the space. Probably a good idea to split this out into it's own component?

**Comment by UnevenCoder** [comment]
so basically kind of sticking em together ?

**Comment by sw-yx** [comment]
this is being worked on by #88
