### ISSUE TITLE
Combine "Developer Experience" components with Tooling page

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#22]
Everything listed here would be more applicable on the Tooling page:
https://sveltesociety-2021-dqq.pages.dev/components#category-Developer%20Experience

The Tooling page should probably use the same system as the Components and Boilerplates pages. Those two pages have lots of copy/pasted code and so should be refactored

**Comment by kevmodrome** [comment]
Yeah, I think that makes sense.
