### ISSUE TITLE
Use SvelteKit ?

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#223]
I noticed the site doesn't use SvelteKit, so I was curious what folks thought about trying out the hot new kid on the block

**Comment by kevmodrome** [comment]
I actually started working on this on Monday, so far I've got the index page and cheat sheet converted! :)

**Comment by benmccann** [comment]
@kevmodrome I missed your comment until now. I've seen people use `import.meta.glob` for that in SvelteKit

Example: https://github.com/mvasigh/sveltekit-mdsvex-blog/blob/4cde064ece9c742b4c30949c440f582468afe0dd/src/routes/index.svelte#L2

Vite docs: https://vitejs.dev/guide/features.html#glob-import

I'm not 100% sure I understood, so let me know if that addresses the issue or if there's some functionality still missing from SvelteKit.

**Comment by kevmodrome** [comment]
Yeah that would work in this case, I suppose. It's just much easier in Routify: https://routify.dev/docs/helpers#layout

In general I think Routify has functionality that makes it a lot faster to access parents, children, siblings, etc.  For example, get the parent, siblings, children, etc. I'm not sure it's even possible to do in SvelteKit?

**Comment by benmccann** [comment]
I've seen several blogs built on SvelteKit that solve basically this same issue. Here's a few I found that hopefully would be good examples.

* Using `import.meta.glob`
  * https://github.com/babichjacob/university-website/blob/84b5e7ff44550910550a3c809ccb9f1402df301b/src/routes/blog/index.json.ts
    * A more advanced way: https://github.com/babichjacob/university-website/blob/84b5e7ff44550910550a3c809ccb9f1402df301b/README.md
  * https://github.com/mvasigh/sveltekit-mdsvex-blog/blob/4cde064ece9c742b4c30949c440f582468afe0dd/src/routes/index.svelte#L2
* Using the filesystem and `marked` directly
  * https://github.com/mhatvan/markushatvan.com/blob/424ca3452a364562e4b01d07ea7efd003a5d05be/src/routes/blog/_posts.ts#L11

Routify does look like it might make this slightly easier though I think the SvelteKit version shouldn't be too much harder. I've seen enough people trying to solve this though that at the very least it's probably worth a mention in the SvelteKit FAQ

**Comment by kevmodrome** [comment]
Right, I'm not saying it wouldn't be doable in SvelteKit, just that it's much easier in Routify:

```svelte
<script>
  import { layout } from "@roxi/routify";
  const nodes = $layout.children;
</script>

{#each nodes as page}
    ...
{/each}
```

**Comment by HAUDRAUFHAUN** [comment]
Do you know if a feature like `layout` form routify is planned to get integrated into sveltekit?

**Comment by benmccann** [comment]
There hasn't been any discussion of it. It'd be useful to see a side-by-side comparison. If there's something that could be made a lot easier then we'd be open to it. I think it's not really much harder in SvelteKit though: `const children = import.meta.glob('./**/*.svx');`

**Comment by HAUDRAUFHAUN** [comment]
This approach looks nice and clean, but it's giving you back an object, not an array (like the `layout.children` would do).

**Comment by HAUDRAUFHAUN** [comment]
I figured out following solution: 
```html
<script>
         // import bloglistelement component
	import BlogListElement from '$lib/BlogListElement/index.svelte';
        
         // get layout children
	const children = import.meta.glob('../**/*.svx');
        
        // convert layout children object to array
	let nodes = Object.entries(children);
</script>

<svelte:head>
	<title>Blog</title>
</svelte:head>

// iterate over array -> remove file extension of .svx files for getting the route
{#each nodes as item}
	<BlogListElement title="Test" description="Test description" url={item[0].replace('.svx', '')} />
{/each}
```

**Comment by HAUDRAUFHAUN** [comment]
I opened up a [Pull Request](https://github.com/svelte-society/sveltesociety-2021/pull/1) on the svelte-kit version of the site, I used a [hook](https://github.com/svelte-society/sveltesociety-2021/pull/1/files?file-filters%5B%5D=.cjs&file-filters%5B%5D=.js&file-filters%5B%5D=.json&file-filters%5B%5D=.svelte&file-filters%5B%5D=.svx&file-filters%5B%5D=.ts#diff-a2d969770fbca6d31b2bcb062b5d406aa54f9ddebef57996faacc6f82e746e42R1-R17) that I found on the gitpod website to resolve this issue.

**Comment by kevmodrome** [comment]
> There hasn't been any discussion of it. It'd be useful to see a side-by-side comparison. If there's something that could be made a lot easier then we'd be open to it. I think it's not really much harder in SvelteKit though: `const children = import.meta.glob('./**/*.svx');`

I think you're looking at this from a PoV that is too "narrow" if that makes sense. The idea of the layout helper isn't only to give you access to a list of children in some path, among other things it also lets you traverse the manifest file programatically and provides you with a ton of information about each route. Here's an example of the amount of information you have access to using just the `$layout` helper:
<img width="1277" alt="CleanShot 2021-05-18 at 11 37 03@2x" src="https://user-images.githubusercontent.com/534488/118629150-9ae7e700-b7cd-11eb-87b9-8d934d225d12.png">

**Comment by mvasigh** [comment]
Hi! I'm interested in this issue since I recently did something similar. Curious, what are the most useful bits of info exposed by the Routify utility? 

`import.meta.glob` does give you paths and I feel like you could reconstruct most of that tree from just the paths, but I'd like to know which parts are most important/useful.

**Comment by kevmodrome** [comment]
> Hi! I'm interested in this issue since I recently did something similar. Curious, what are the most useful bits of info exposed by the Routify utility?
> 
> `import.meta.glob` does give you paths and I feel like you could reconstruct most of that tree from just the paths, but I'd like to know which parts are most important/useful.

I think this discussion has mostly evolved into a discussion about why it would be nice to have something equivalent to `$layout` in SvelteKit. We've already established that it can be done.

I'm sure you can re-create most functionality using import.meta.glob, I'm merely saying that doing things like this in Routify requires much less effort. 

One thing I find myself using in Routify is the ability to specify metadata. Another thing you can do is specify an order using an index attribute. You can easily check if something is a DIR or a PAGE, conditionally check if something is a layout, etc. etc. This would all be possible to get at from this helper.

You can easily get the previous/next sibling - this would let you very easily make a "Next Post" kind of thing at the bottom of blog posts.

**Comment by mvasigh** [comment]
Yeah all of that makes sense! I've never used Routify, but did run into some of those limitations of SK while building with it (and I'm pretty new to Svelte's ecosystem in general). So this is useful for me to think through in my head what I'd want this kind of functionality in SK to look like.

**Comment by algaly** [comment]
> I actually started working on this on Monday, so far I've got the index page and cheat sheet converted! :)
> 
> Edit: I do think there will be some irritating issues going from Routify to SvelteKit though. We're relying heavily on the `layout.children` functionality of Routify which basically [lets us fetch all children on a route](https://routify.dev/docs/helpers#layout) (and use those in a menu for example). This in turn makes it possible for contributors to pretty much just create a file in the Recipes folder and everything will update automatically.

SvelteKit is Great !
Don't worry you'll edict to it.

**Comment by algaly** [comment]
I was wondering how can i config an ssl with sveltekit with the ssl certificate i bought

**Comment by benmccann** [comment]
@algaly please ask this type of question in the #svelte-kit discord channel. It's way off topic for this issue

**Comment by davidwparker** [comment]
> I actually started working on this on Monday, so far I've got the index page and cheat sheet converted! :)

@kevmodrome - if you have a PR you can push up, I can start working on this. I have some free time and would like to help where I can.

**Comment by benmccann** [comment]
There's a repo for it at https://github.com/svelte-society/sveltesociety-2021. I sent a PR https://github.com/svelte-society/sveltesociety-2021/pull/4 that finishes up a lot of what's left. Hopefully @sw-yx or @kevmodrome can merge so that people can work from that base. It'd be helpful to test all the various links and features and check out what might still be missing compared to the live site, polish rough edges, etc.

**Comment by sw-yx** [comment]
yes we do... sorry just got a little busy at work. merging now

**Comment by benmccann** [comment]
thanks @sw-yx! @davidwparker if you have some time to lend, I just made a list of stuff that I noticed is different between the sites: https://github.com/svelte-society/sveltesociety-2021/issues/5. There's not too much, so hopefully we're just another PR away from being in a launchable state!

**Comment by sw-yx** [comment]
just gonna close for now since work is underway
