### ISSUE TITLE
Add podcast and newsletter

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#242]
@d3sandoval and @kevmodrome have both pointed out that the newsletter isn't very discoverable from svelte.dev currently. There's been some hesitation about putting it on svelte.dev since no one wants to take on the burden of being responsible for making it official. But sveltesociety.dev seems like a great place for it to live since it's the community site. And then I'd like to do a better job surfacing sveltesociety.dev on svelte.dev after we finish doing some of these things

I think that putting a link to the [podcast](https://www.svelteradio.com/) and [newsletter](https://svelte.substack.com/) on the homepage next to the YouTube, Twitter, and Discord links could be a good place to surface it

**Comment by benmccann** [comment]
https://www.iconfinder.com/iconsets/social-hand-drawn-icons

**Comment by kevmodrome** [comment]
Sorry, must have missed this - GitHub notifications aren't the best. I think this makes sense.

**Comment by benmccann** [comment]
This was done in https://github.com/svelte-society/sveltesociety-2021/pull/6. Thanks to @brittneypostma!
