### ISSUE TITLE
Find/Design icons that fit with each Recipe category

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#25]
We need icons for each recipe category, at the moment we only have a "key" as a placeholder.

**Comment by sw-yx** [comment]
- https://logosear.ch/ superfast metasearch of 200k svg logos from GitHub
- https://thenounproject.com/ Every icon you can think of, in PNG or SVG formats. They offer over 20 million icons, with built-in customization colors like size and color. Requires login, needs creative commons attribution or $3 download
- https://hotpot.ai/free_icons 5,000+ free icons. Customize colors, size, and other properties. PNG, JPG, iOS, Android, PDF. No svg.
- **https://iconmonstr.com/** Discover 4486+ free icons in 310 collections. SVG, EPS, PSD, PNG. [OK without attribution, don't sell it](https://iconmonstr.com/license/).
- https://icomoon.io/ - 450 icons, SVG, PDF, EPS, Ai, PSD. Paid tier goes up to 1600 icons.
- https://orioniconlibrary.com/ has customizable colors and packs eg for ecommerce
- https://material.io/resources/icons/?style=baseline
- http://www.entypo.com/
- https://www.heroicons.com/
- https://feathericons.com/
- https://www.zondicons.com/
- animated icons http://www.transformicons.com/builder.html
- https://game-icons.net/
- brand icons
  - http://simpleicons.org/ icons for every brand like graphql, adobe xd, youtube, etc
  - https://css.gg/ 700+ Customizable & Retina-Ready app icons — entirely built in CSS 
  - https://worldvectorlogo.com/

**Comment by babycourageous** [comment]
Maybe we can come up with our category list here (not sure if it will wind up being different than what's currently at the MVP) then a text description of the icon to be on the hunt for? 
I can get the ball rolling if that interests ya.

**Comment by stephane-vanraes** [comment]
it's not only icons that fit with the category, they also have to fit with each other and the overall styling of the page

for categories we have

- **build setup** some construction material ? like a pile of bricks ?
- **components** 
- **design patterns** cog wheel, machinery ?
- **other** we should try to get rid of this category all together imo
- **publishing and deploying** something with paper perhaps ?
- **stores** shop front ? box ?
- **language fundamentals** is this even a recipe ? it's more of an enhanced tutorial
- **testing and debugging** bug ?

**Comment by babycourageous** [comment]
@stephane-vanraes 100% on the fitting with each other.

**Comment by Wolfr** [comment]
Don't give yourself design problems you can't solve. What about no icons?

**Comment by sw-yx** [comment]
will put this discussion on ice for now since we have a kinda working recipe page
