### ISSUE TITLE
REPL Component

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#26]
At some point we'll be using the [REPL](https://github.com/sveltejs/svelte-repl). It should be easy enough to import and needs to be imported dynamically as to not be too heavy for users.

**Comment by stephane-vanraes** [comment]
Could you be more specific as to where and how you would use it?

**Comment by kevmodrome** [comment]
The intention is for using this inside of the recipes in order to make a more interactive experience for the users. 

The author for would make a REPL on the official Svelte website, save it and extract the ID used. This ID will be used to fetch a json file at build time and pass the source of that to the REPL's `content` prop. Here's an [example of a JSON file](https://svelte.dev/repl/f807be09c1d645d583cb9476a194edde.json). This matches [this REPL](https://svelte.dev/repl/f807be09c1d645d583cb9476a194edde).

**Comment by stephane-vanraes** [comment]
ok so should be as easy as doing `<Repl id="123" />` from an author point of view?

**Comment by kevmodrome** [comment]
yep! that's the idea, if it's problematic to fetch on build it might be possible to fetch the file from the svelte website on runtime

**Comment by kevmodrome** [comment]
I'll go ahead and make this during the weekend

**Comment by sw-yx** [comment]
do we have a working repl component yet kev?

**Comment by sw-yx** [comment]
this work is now being tracked on #93 and pending decisions on the REPL
