### ISSUE TITLE
Search for components: Searching with a text that doesn't match any results breaks the site

### ISSUE THREAD

**Issue by umaranis** [svelte-society/sveltesociety.dev#262]
Steps to reproduce:

1. Go to https://sveltesociety.dev/components/
2. In the 'Search for components...' field, type a text that doesn't match any results (e.g. 'hello')
3. The site stops working at this point
   - the filtration of components stops working
   - links to other pages like Tools stop working
   - following error is reported in the console logs

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at Object.p (sort-582dd570.js:3:2453)
    at Sl (vendor-d78fc752.js:4:1769)
    at Hn (vendor-d78fc752.js:4:1438)`

**Comment by mrienstra** [comment]
Same problem here: https://sveltesociety.dev/tools/

Preparing a fix.
