### ISSUE TITLE
Empty and unnecessary "Unclassified" section

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#292]
https://sveltesociety.dev/tools/

**Comment by MacFJA** [comment]
I think the whole reading/parsing/searching of tools.json, components.json, templates.json need to be rethink.

There are lots of errors and weird behavior.

**Comment by MacFJA** [comment]
After some testing, it appear that the "Unclassified" section shouldn't be empty.
There are 2 tools that should appear in it
