### ISSUE TITLE
Cookbook Features

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#3]
This issue is to discuss what things should be present on the Cookbook page.

There are a number of ways figure this out I think. I quite like the [Vue](https://vuejs.org/v2/cookbook/) and [Phoenix](https://hexdocs.pm/phoenix/overview.html) cookbooks/guides. They both seem to go for a sidebar with sections and recipes and then display the content in the middle. This would fit well with the current design that keeps a navigation bar at the top.

For the recipes themselves I think the way the Vue cookbook does it is good. It's a simple markup page that contains the content. In the future (Phase 2) we can improve on this concept a bit by adding MDSveX support. This would make it possible to add support for the REPL. Depending on the recipe this can be quite helpful for users.

**Comment by sw-yx** [comment]
think we already have this one sorted
