### ISSUE TITLE
Add svelte version to recipes

### ISSUE THREAD

**Issue by stephane-vanraes** [svelte-society/sveltesociety.dev#30]
Should we add a svelte version to recipes ?

This would make it clear for readers that if a recipe was last verified for version **3.13** and we are now **3.178** that it might be out dated.  If we add this, an additional change could be to during build check against the current svelte version and somehow mark the recipes that are a predefined number of versions behind with a little warning.

Pro:
- removes responsibility of maintainers to check if each recipe is still ok
- _might_ encourage other people to keep the recipes up to date

Contra:
- risks having a plenty of recipes marked as potentially outdated, this would not look very 'professional'
- adds extra pressure to maintainers to verify recipes

**Comment by kevmodrome** [comment]
There was also a good idea by @trbrc to also version dependencies. Say for example if the recipe involves postcss, there should probably be a version noted for that.

**Comment by kevmodrome** [comment]
We could implement this as an action, probably. That way it would automatically be a sort-of progressive enhancement. I'm biased though, so open to other ideas 😬

**Comment by sw-yx** [comment]
seems like an easy one to do, keep open

**Comment by sw-yx** [comment]
i now think this is unnecessary. we dont break api's that often. we should call out if a recipe takes advantage of a new feature but just make it easy for people to report breakages in recipes.
