### ISSUE TITLE
Docker recipe gives bad advice

### ISSUE THREAD

**Issue by Conduitry** [svelte-society/sveltesociety.dev#31]
The Docker example at https://staging.sveltesociety.dev/recipes/publishing-and-deploying/dockerize-a-svelte-app has some issues. Using it as-is will include all of your dev dependencies in the built image. And using Node in production to serve static assets is also probably undesirable.

At the very least, this should use a two-stage Dockerfile, the second of which only installs production dependencies and copies over the built files from the first stage. But also perhaps it should use a dedicated lightweight static file host for the final stage. I don't really have strong opinions about what that ought to be. It's certainly fewer decisions to make just having it continue to be Node and `sirv`.

**Comment by kevmodrome** [comment]
Thanks for the review, I'm not very experienced with Docker, if anyone is this is up for grabs!

**Comment by kevmodrome** [comment]
Thinking a bit more about this, should we maybe have a recipe on how to deploy a Sapper app, rather than a Svelte app? It's probably true, as you say, that just deploying static stuff using docker is a bit odd.

**Comment by antony** [comment]
@kevmodrome I'm unlikely to have any time, but the Svelte site itself has a working and secure docker config that could just be dropped in for starters.

**Comment by kevmodrome** [comment]
Got it! 

I'll see if I can find time and motivation this week-end (I'm starting to sound like a broken record at this point) to update this. Will look at the Svelte site one. Cheers!

**Comment by Conduitry** [comment]
This does appear to have been fixed some time ago, but never closed.
