### ISSUE TITLE
Lightweight calendar for svelte easily integrated with any popular frameworks

### ISSUE THREAD

**Issue by Sanshain** [svelte-society/sveltesociety.dev#327]
Lightweight calendar for svelte easily integrated with any popular frameworks

![image](https://user-images.githubusercontent.com/40761960/195413517-d5dfefe7-7ab9-4ee7-bf9b-1dbf8c1829db.png)

https://github.com/Sanshain/svelte-color-calendar

**Comment by benmccann** [comment]
You can submit a PR to add it if you'd like. We don't add much ourselves and rely on authors and the community to do it
