### ISSUE TITLE
Adding a real recipes index page

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#34]
Do we want to add real recipes index page like the one in the [design](https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=172%3A0) or is it better to go with what we currently have?

**Comment by stephane-vanraes** [comment]
Currently the index pages for /recipes and /recipe/[category] are kind of dull, it would not harm to have something there.  For the category pages a description of what kind of recipes can be found there would be helpful (also aids contributors to place their recipe in the correct one)

**Comment by kevmodrome** [comment]
Agreed! I think we should go ahead with the design I linked for `/recipes` i'm going to open that up as a good first issue

**Comment by ChaitanyaGadodia** [comment]
Hi, I am picking this task as per the designs added above

**Comment by kevmodrome** [comment]
@ChaitanyaGadodia did you get started on this?

**Comment by ChaitanyaGadodia** [comment]
No I haven't yet started, but I will submit the PR by Saturday evening. Swamped with work, will start first thing on Friday evening.

**Comment by kevmodrome** [comment]
No stress, just wanted to see if you needed anything 👍
