### ISSUE TITLE
Anchor links to site are broken

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#342]
Anchors don't work. E.g. if you go to https://kit.svelte.dev/docs/integrations and click "available preprocessors" it will take you to https://sveltesociety.dev/tools#preprocessors, but then that doesn't scroll to the correct location and just stays at the top of the page

It's probably because the data to display is only set after the search event is dispatched: https://github.com/svelte-society/sveltesociety.dev/blob/staging/src/routes/searchableJson.svelte#L53

**Comment by benmccann** [comment]
Fixed here: https://github.com/svelte-society/sveltesociety.dev/commit/3877a1ede6f45b3e0c31ed29e2353bd5ad9e03f4

Pushed without a review to get the site working again before the special episode of Svelte Radio on Dec 14

**Comment by benmccann** [comment]
I thought I'd fixed this, but it doesn't seem to have been fixed actually

**Comment by benmccann** [comment]
Any help would be appreciated! I probably won't be able to get back to this for the rest of the year

**Comment by MacFJA** [comment]
Probably because the page at server side is empty.
Seem like the SSR can't find all the items

----

`curl https://sveltesociety.dev/tools#preprocessors`
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />

<!-- ... -->

<a href="/help/submitting?type=tool" class="submit">Submit a tool</a></div>
<input class="searchbar" type="text" placeholder="Search for tools..." value="">
<span class="searchbar-count">0 results</span></section>
<hr>
<section slot="items"></section></main>

<!-- ... -->
```

**Comment by benmccann** [comment]
many thanks to @gtm-nayan for figuring out this was fixed, but not deployed due to a broken build!
