### ISSUE TITLE
Pin this repo to the org? Also—some broken link callouts

### ISSUE THREAD

**Issue by andrewjroberts** [svelte-society/sveltesociety.dev#346]
Hi all,

Some fwiw/2 cents comments:

- This repo seems to be the new place for most things svelte-society, should we pin it in svelte-society org?

- Don't think two archived repos necessarily gives off a super welcoming feeling:

<img width="1792" alt="Screen Shot 2022-12-17 at 10 22 40 AM" src="https://user-images.githubusercontent.com/101012384/208249036-0fc0da65-2c20-4e52-9226-7f704dd48ff6.png">

- The sidebar description/README links in https://github.com/svelte-society/recipes-mvp are broken:
  - broken link for reference: https://github.com/svelte-society/sveltesociety.dev/tree/staging/src/pages/recipes
  - correct link for reference: https://github.com/svelte-society/sveltesociety.dev/tree/staging/src/routes/recipes
  - <img width="522" alt="Screen Shot 2022-12-17 at 10 23 03 AM" src="https://user-images.githubusercontent.com/101012384/208249059-b96d2add-e48d-4942-89aa-bcdd9ebb2aee.png">

**Comment by benmccann** [comment]
I don't know if we can keep links updated in archived repos, but we've updated which repos are pins. Thanks for the callout!
