### ISSUE TITLE
Recipes pages are unsuable on small screens

### ISSUE THREAD

**Issue by pchynoweth** [svelte-society/sveltesociety.dev#35]
The recipes pages don't fit on smaller screens.  The most obvious solution would be to enable flex wrapping and set a minimum width for the article.  I'm sure someone with a better eye for design can think of something better.

**Comment by kevmodrome** [comment]
Yep! Currently the whole website is not particularly mobile friendly. It needs to be designed before we can build it!

**Comment by stephane-vanraes** [comment]
#42 improves on  the layout by moving the reicpe-list on top for smaller screens.

This is still not  ideal though, as it introduces a large scroll requirement.
Further improvement could be to have them as a dropdown on small devices.

**Comment by kevmodrome** [comment]
I think the latest merge might have been a bit to aggressive on the media query width
