### ISSUE TITLE
Site doesn't build

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#35]
I just realized `npm run build` fails. That's probably the biggest thing we need help with to get this launched. Any help would be appreciated

**Comment by ambarvm** [comment]
Can I help with this?

**Comment by ambarvm** [comment]
Found a few issues that are causing the build to fail. 
- img tags for icon in Recipe and RecipeCategory result in 404. I guess the Icon component is supposed to be used here.
- stores recipe has a broken link to `tutorial/store-bindings`
- A url typo in index.svelte

Also Not a build error but font url needs to start with / to work in build

**Comment by benmccann** [comment]
Yes, any help would be very much appreciated
