### ISSUE TITLE
Update Parcel tools

### ISSUE THREAD

**Issue by PixievoltNo1** [svelte-society/sveltesociety.dev#448]
Presently, the only Parcel plugin listed on the website is for v1, which is nearly 2 years out of date. Several Svelte plugins exist for v2; the one I would recommend out of these is [parcel-transformer-svelte3-plus](https://github.com/HellButcher/parcel-transformer-svelte3-plus), which supports Svelte 4 and svelte-preprocess, and has an author who's been responsive to my issue reports.

I'm willing to write a PR to update the plugin info once these questions are answered:
- Is it acceptable to submit a plugin I don't maintain, or would you rather I ask the author to submit the plugin themselves?
- Should I remove the v1 plugin altogether, or just amend the description to say it's for v1?

**Comment by benmccann** [comment]
You can definitely add a plugin you're not the author of

I suppose for now I'd leave the v1 plugin and just update the description. There's probably a number of old plugins and we're considering how to show more info like last-updated date, etc.
