### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/sveltesociety.dev#45]
"site" is a bad name. When cloning I had to change it to something recognizable.

Suggestion: change `site` to `svelte-society-site`.

<img width="304" alt="Screenshot 2020-07-22 at 21 44 20" src="https://user-images.githubusercontent.com/12690/88221274-85b13300-cc64-11ea-9cff-b9a43576bbaa.png">

**Comment by kevmodrome** [comment]
I'm not sure this is a big enough problem, you can just `git clone svelte-society/site yourFolderNameHere`. Does GitHub automatically redirect if we change it? If so I'm fine with changing it! :)

**Comment by Wolfr** [comment]
Yes - github will redirect!

Verstuurd vanaf mijn iPhone

**Comment by stephane-vanraes** [comment]
In several projects I have seen the repo take it's name from the url, so in our case this would be `sveltesociety.dev` as repo name

**Comment by Wolfr** [comment]
Great idea @stephane-vanraes !

**Comment by kevmodrome** [comment]
Let's rename it to that, i'll sort it out.
