### ISSUE TITLE
Stores intro markdown problem

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/sveltesociety.dev#46]
<img width="975" alt="Screenshot 2020-07-22 at 21 48 14" src="https://user-images.githubusercontent.com/12690/88221661-1982ff00-cc65-11ea-9dd4-88941ce5eb06.png">

Stores intro has some markdown that is not parsed.

https://staging.sveltesociety.dev/recipes/stores

**Comment by stephane-vanraes** [comment]
This is an issue with mdsvex, it does not parse the slotted content of inlined components.

We should write the links out in a regular way (or perhaps have a `Link` component to easily share styleing)

**Comment by kevmodrome** [comment]
I believe this will be fixed in an upcoming version of MDSveX, but I think it's still pretty far off

**Comment by darotar** [comment]
@kevmodrome I am not sure about fixing, found [an article](https://daringfireball.net/projects/markdown/syntax#html) that markdown doesn't even go inside html blocks

**Comment by kevmodrome** [comment]
fixed by #50
