### ISSUE TITLE
Lots of PR out of sync

### ISSUE THREAD

**Issue by MacFJA** [svelte-society/sveltesociety.dev#465]
- Lots of PRs are in conflict and need to be rebased
- Lots of PRs have code style issue

---

**What should we do ?**

- Close all PRs in those that have more than X days ?
- Add a comment on all PRs to ask the author to update them ?
- Should I fix all of them ?

_I'm not for fixing all PRs, I fear that people will not do any effort in the future as "eventually, someone will fix my PR"_

---

Should we remove the prettier check on `components.json`, `tools.json`, `templates.json` ?
Because it appears quite clearly that submitters don't install the repo (because husky is installed, and it runs automatically prettier before committing) nor run prettier manually

---

Your thoughts on this @benmccann @kevmodrome

**Comment by benmccann** [comment]
My thought was that if we first simplified the process of submitting libraries by automating more stuff (https://github.com/svelte-society/sveltesociety.dev/issues/443) then it wouldn't be so hard to just submit the libraries from the PRs ourselves

**Comment by MacFJA** [comment]
I guess @lachlancollins is doing it anyway
