### ISSUE TITLE
showcase page

### ISSUE THREAD

**Issue by stephane-vanraes** [svelte-society/sveltesociety.dev#47]
inspiration: https://www.gatsbyjs.org/showcase/

goal: draw attention to potential users of svelte that it can be more than 'toy projects'

projects submitted by PR

features:
- tagging projects (fashion, design, ...)
- curating a list of 'featured'

more discussion required

**Comment by AnnieTaylorCHEN** [comment]
Maybe good to think about : who will be visiting this page? Agency? Clients? Tech lead who decides tech stack for new projects? Startup founders? Front-end developers who wants alternatives than bigger three? 

Each group will have different knowledge background and focus. Clients will care about whether the use case also solves their own problem. Tech lead cares about whether they have enough hands with tech skills to get things done before deadline and long-term maintainability of the projects. Startup founders want to know if they can use the tool to prototype as fast as possible to release to market. Developers just want to if they can spend less time to write code that does the same thing. 

In my opinion, Svelte's current site is more focused on developers but not the end users. But many times, it is the end users that have a say. Developers, unless a tech lead, usually follows the guideline set by others.

**Comment by sw-yx** [comment]
great questions from Annie :) so is this a "pitch your boss" page? maybe that deserves a 1 page brochure rather than a showcase.

**Comment by AnnieTaylorCHEN** [comment]
Hmm, I think that could do too. Maybe different pages for different audiences?

A good point to think about is also: What are the reasons people aren't picking Svelte for real-world production ready projects? Maybe need a bit more user research for that. If we can send a survey to tech leads or CTOs who made decisions on tech stack on new projects, we can get something to target on. At least I feel a lot of developers are enthusiastic about it, but they are not the decision makers, which hinders the adoption of Svelte. 

One thing we don't have, compared to Gatsby, is that it's built upon React, and React already has a large "fan base". It's not a big jump from React to Gatsby. To me from React to Svelte is a better jump, but it might not be to others.

**Comment by stephane-vanraes** [comment]
Another thing we should not forget is who is going to add the pages, and the extra effort or thresholds goes with that.

In all likelyhood pages will be added by developers that worked on those projects.  Should we expect them to write something more substantial about the project ? (Looking back at the gatsby page, each sample only has an image, short text and some keywords)

**Comment by AnnieTaylorCHEN** [comment]
For curated cases, we can have more details, maybe more screenshots or even video, description on benefits of Svelte provides for the projects etc. This will be probably less than 15-20. This should be maintained by Svelte-team. I can help with that! ^^

For other show cases, we can make a similar gatsby page. Developers submitted projects, someone reviews the PR, then merge. More people use that, we will have more volunteers too. I am not sure how to build this "pipeline" but would be happy to learn if someone can show me.

**Comment by kevmodrome** [comment]
I'm thinking something like this: A "big" carousel-style" thing at the top that shows the featured sites/pages and then a list like the Gatsby one below that. We need to make sure it is visually different from the component listing page found here: https://staging.sveltesociety.dev/components. The current design document is here: https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=35%3A2 if anyone is interested in getting started designing this you can duplicate the document. Try to keep it in-line with the look and feel of the design! 👍 I've also gone ahead and opened a new issue that specifically is about the design here #49

**Comment by sw-yx** [comment]
keeping this open

**Comment by AnnieTaylorCHEN** [comment]
It's been a while.... took me a while to onboard with the job. Do we have a team where you can add me and we can reuse component in the team? I think it would be easier to gather all the designs under one roof.
