### ISSUE TITLE
Design for Showcase page

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#49]
We need a design before we can get started implementing the Showcase page. The current design document for the site is here: https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=35%3A2

If you are have a good eye for design and want to give it a shot, duplicate it and try making something cool! 👍

**Comment by sw-yx** [comment]
still vlaid

**Comment by sw-yx** [comment]
just going to consolidate this on #47
