### ISSUE TITLE
Parity with sveltesociety.dev

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#5]
Here's a list of things I noticed that are different between this repo and the production site:

* ~~favicon is missing (https://github.com/svelte-society/sveltesociety-2021/pull/13)~~
* ~~page titles are missing - for homepage, components, boilerplate, cheat sheet, events (https://github.com/svelte-society/sveltesociety-2021/pull/13)~~
* ~~`robots.txt` - renders the homepage instead of a valid robots.txt file (https://github.com/svelte-society/sveltesociety-2021/pull/19)~~
* ~~events page - most past events are missing (https://github.com/svelte-society/sveltesociety.dev/pull/36)~~
* ~~recipes - text is very large on individual recipe pages and recipe category pages (https://github.com/svelte-society/sveltesociety.dev/pull/32)~~
* boilerplates and components - controls are misaligned and missing arrow icon ~~(https://github.com/svelte-society/sveltesociety.dev/pull/41)~~
* ~~CSS stacking issue? If you visit all the pages a couple times you will start to see the page squished to the left hand side of the screen. Is there some CSS from an old page not being removed? (https://github.com/svelte-society/sveltesociety.dev/pull/42)~~
* ~~`npm run build` fails (https://github.com/svelte-society/sveltesociety.dev/issues/35)~~

**Comment by kevmodrome** [comment]
This is a good list. I'll post on Twitter and on Discord and see if we can get some people interested in helping with this.

**Comment by christianp86** [comment]
Happy to help 🙌🏻

**Comment by benmccann** [comment]
That'd be great @christianp86! Any idea when you might be able to take a look?

**Comment by christianp86** [comment]
@benmccann I will take a look tonight. Should we create individual issues for better tracking?

**Comment by benmccann** [comment]
no need. I can just update the list above as PRs are merged to cross out items that are done

**Comment by christianp86** [comment]
I'll try fixing some more issues this week 👍🏻

**Comment by christianp86** [comment]
Sorry guys but finding time during my parental leave is harder then expected 🙃 I did some additional fixes for events but then my little girl woke up from her nap 😴 
Long story short I am on vacation for two weeks now and will get back to it once we are home again. Cheers chris

**Comment by benmccann** [comment]
@kevmodrome there's a good handful of PRs pending. Once they're all merged I think we should be good to launch!!

**Comment by kevmodrome** [comment]
Closing this since we've launched!
