### ISSUE TITLE
Proposal: some more repo setup

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/sveltesociety.dev#51]
Let's improve the onboarding for newcomers to this repo.

This is what people will currently see:

![image](https://user-images.githubusercontent.com/12690/89121365-93658480-d4be-11ea-80f2-52b0d6894ef1.png)

* I would propose to link to https://sveltesociety.dev/ in the repo description so you can directly click through to the website

* In the About section I would change copy from

> wip: future site for recipes, component library, examples, tutorials, events, talks etc

to 

> Community website for Svelte Society (Work in progress). The site will contain a component library, Svelte examples, tutorials, event information, talks etc.

Within the README, I would put another description, but I will leave that work a PR.

**Comment by kevmodrome** [comment]
Good ideas! I'll update the description and and add a link to the site.
