### ISSUE TITLE
Create more Github issue/PR template

### ISSUE THREAD

**Issue by MacFJA** [svelte-society/sveltesociety.dev#518]
Right now we have one template for all PR (see #513)

It could be nice to have several templates to simplify even more the contribution and the validation.

What we could have is:
 - One PR template for adding/updating a component/tool/template
 - One issue template for requesting changes
 - One PR template for deletion (component/template/tool)
 - One PR template for other changes

**Comment by kevmodrome** [comment]
Closing as this will be changed majorly in V2.
