### ISSUE TITLE
Improve the README

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#52]
We need to improve the readme to describe what the project is about, how to contribute, etc.

**Comment by UnevenCoder** [comment]
I would love to help ... can I know more like how do you want it ?

Hierarchy of events etc 
Thanks

**Comment by sw-yx** [comment]
we should still work on the Readme 👍

**Comment by Isaac-Tait** [comment]
I can take a crack at this and submit a draft in a few days if it would be helpful.

**Comment by sw-yx** [comment]
thanks so much Isaac :)
