### ISSUE TITLE
Dev/Staging/Prod - What do we do?

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#548]
Since we're moving to a Database based setup in the next version I thought it'd be nice to discuss how we want to handle Dev/Staging/Prod environments.

V1 lives on Cloudflare Pages so not much to think about there.

For V2 we keep the actualte Kit part on Cloudflare but introduce a backend (PocketBase). This server is hosted on our own server running [Coolify](https://coolify.io). I asked on the PocketBase repo how other folks handle this: https://github.com/pocketbase/pocketbase/discussions/4004

I'm thinking a monorepo loosely based on https://github.com/jonshipman/sveltekit-pb-boilerplate

Thoughts?

**Comment by benmccann** [comment]
The ideal in my mind is previews that we can see and test against with each PR and then `main` gets deployed to production

**Comment by kevmodrome** [comment]
Closing this since it's very old - we're going with Vercel to handle the frontend and Turso as the DB, working on setting up staging and prod environments. Dev can be done locally using SQLite via the Turso CLI.

Went with monorepo structure
