### ISSUE TITLE
Broken link at /about

### ISSUE THREAD

**Issue by fedeperin** [svelte-society/sveltesociety.dev#566]
The link at /about in "License Information" is broken 

![image](https://github.com/svelte-society/sveltesociety.dev/assets/83504427/6a90e503-eb13-4944-83b5-d721613dc443)

**Comment by lachlancollins** [comment]
Hi @fedeperin , thanks for reporting! @kevmodrome , do you know where `/licenses` is meant to link to?

**Comment by MacFJA** [comment]
It's more @benmccann that will have the information: https://github.com/svelte-society/sveltesociety.dev/commit/ec7dcb3efd9be77f039f66825f38f0a00f3461ac

But looking at the old website it's this file: https://github.com/svelte-society/sveltesociety.dev-legacy/blob/staging/src/pages/licenses.svx

**Comment by benmccann** [comment]
I just migrated it from old site to new site. I'm afraid I don't have any context about the information contained there
