### ISSUE TITLE
Add Plausible back to the master branch

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#58]
Plausible was accidently removed from the master branch when I merged the new site and thus we don't have any analytics anymore. This is a good first issue. This snippet needs to be added to the head tag to the html file:

```
<script async defer data-domain="sveltesociety.dev" src="https://plausible.io/js/plausible.js"></script>
```

**Comment by UnevenCoder** [comment]
Is this done ?

**Comment by kevmodrome** [comment]
Yes!
