### ISSUE TITLE
Recipe request for bench marking svelte components

### ISSUE THREAD

**Issue by TheComputerM** [svelte-society/sveltesociety.dev#60]
There is no real guide out there on a good way to benchmark different svelte components.

**Comment by kevmodrome** [comment]
Sounds like a good idea! Do you want to give it a go?

**Comment by TheComputerM** [comment]
I do not have much experience with benchmarking, but will give it a go.

**Comment by TheComputerM** [comment]
Under which section (*build-setup/testing-and-debugging/...*) should I put the recipe in?

**Comment by stephane-vanraes** [comment]
I would say benchmarking would fall under _testing/debugging_

**Comment by ryanatkn** [comment]
Related, I've been looking for information and guidance about using the immutable compiler flag. I've been keeping it on and opting out when a component's data structures don't permit, but there's a lot of details I haven't figured out.

**Comment by kevmodrome** [comment]
@ryanatkn that's interesting! What did you figured out so far? This would make a nice recipe IMO

**Comment by TheComputerM** [comment]
Cannot figure out how to properly benchmark the components. This might be useful: https://web.dev/rail/

**Comment by sw-yx** [comment]
nice to have, but i also have no idea how to benchmark (or what we are benchmarking)

**Comment by TheComputerM** [comment]
1) Time taking for component to render.
2) Response time after event is fired
3) How much resources is the component consuming.

**Comment by sw-yx** [comment]
we have a recipe stub - if people can contribute this lets let them reopen later. i dont particularly have any ideas on benchmarking beyond whats already listed in #91
