### ISSUE TITLE
Section on Testing the ContextAPI is unintelligible (to a newb)

### ISSUE THREAD

**Issue by pboling** [svelte-society/sveltesociety.dev#617]
Points of confusion:

1. There are so many referenced files that are not in evidence.
2. Directly after the preface says that we would create a test component to test the context, there are references to a `Parent` component and `OriginalParentComponent` that exit somewhere else?
3. The examples are not provided with file names, but then are referenced in the final test source as if we knew what the filenames were somehow.
4. One file has `setContext`, while the other has `getContext`, but only one of them is referenced as `ContextTest`... ? 
5. `setContext` is imported from `svelte`, but `getContext` is not?

Feeling very lost.

This is my first attempt at writing a test in svelte, and I'm clearly in way over my head, but I think users like me are a target for this documentation, so I hope sharing my confusion can help improve the docs!

ref: https://www.sveltesociety.dev/recipes/testing-and-debugging/unit-testing-svelte-component (bottom of page, final section)

**Comment by kevmodrome** [comment]
Yes, much of the recipes on the site are extremely outdated - with the launch of the new website (~end of the month) there will be fresh material as well as dates and other things to make sure you know as a user that things are fresh!
