### ISSUE TITLE
500 Internal Error on sveltesociety.dev/packages

### ISSUE THREAD

**Issue by marcustrp** [svelte-society/sveltesociety.dev#684]
https://www.sveltesociety.dev/packages displays a 500 Internal Error message.

**Comment by MacFJA** [comment]
I can reproduce the issue locally.

**Comment by MacFJA** [comment]
Issue was introduced with commit a2a18cd36e3530688afe000b63e2a0eef2a7ffbb

**Comment by MacFJA** [comment]
The problem is now fixed.

Thank you @marcustrp for signaling the issue !
