### ISSUE TITLE
JSR Support

### ISSUE THREAD

**Issue by Malix-Labs** [svelte-society/sveltesociety.dev#699]
Hey folks !

Currently, Svelte Society only supports NPM :

https://www.sveltesociety.dev/help/submitting?type=package

Would it be possible to also support [JSR](https://jsr.io/) ?

**Comment by MacFJA** [comment]
To be exact, we support NPM (and NPM-compatible, like PNPM and Yarn) and Ruby (RubyGen and Bundler).

So adding JSR wouldn't be an issue.

How I imagine it:
 - a new key (`jsr`) will be allowed in `packages.json` to put the JSR package name
 - On the website, a new package manager (`Deno`) will be added for `NPM` group (which will be renamed to `TS/JS`)
 - On the website for each package
   - If the package manager is `Deno`
     - for a NPM package, the command will be `deno install npm:sax`
     - for a JSR package, the command will be `deno install @luca/cases`
   - If the package manager is `NPM`
     - for a NPM package, the command will be `npm install sax`
     - for a JSR package, the command will be `npx jsr add @luca/cases`
   - If the package manager is `Yarn`
     - for a NPM package, the command will be `yarn add sax`
     - for a JSR package, the command will be `yarn dlx jsr add @luca/cases`
   - If the package manager is `PNPM`
     - for a NPM package, the command will be `pnpm add sax`
     - for a JSR package, the command will be `pnpm dlx jsr add @luca/cases`

**Comment by MacFJA** [comment]
@Malix-Labs The JSR support have been added last week
