### ISSUE TITLE
Typo in https://sveltesociety.dev/templates#component-svelte-add/bulma

### ISSUE THREAD

**Issue by sharon-wang** [svelte-society/sveltesociety.dev#72]
Noticed there's a typo `Bluma` instead of `Bulma` in the Templates section:
![image](https://user-images.githubusercontent.com/25834218/130459799-f0244204-cb0d-4e24-a120-8f1e3e50497d.png)

I briefly looked into how this can be fixed -- the content for the Templates is in https://github.com/svelte-society/sveltesociety.dev/blob/main/src/routes/templates/templates.json, but it seems like a tool/script might be run to generate/populate this file? It looks like the file is a cache of the template repo info, and running the tool/script would update the stars and descriptions for each repo.

Maybe someone can point me to where that tool/script might be, or let me know if directly modifying the json file is the way to go. Thank you!

**Comment by benmccann** [comment]
it's just done manually for now. I sent a PR to fix

**Comment by sharon-wang** [comment]
Sweet, thanks @benmccann!
