### ISSUE TITLE
Site title

### ISSUE THREAD

**Issue by Wolfr** [svelte-society/sveltesociety.dev#73]
We should change the title of the site to simply "Svelte Society"

The day was the event, this is over now ;)

<img width="561" alt="Screenshot 2020-09-23 at 18 52 13" src="https://user-images.githubusercontent.com/12690/94044032-ea584d80-fdcd-11ea-98c8-e3652adfed67.png">

**Comment by sw-yx** [comment]
yea just noticed it too
