### ISSUE TITLE
add reddit icon to homepage

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#77]
perhaps we should link to https://reddit.com/r/sveltejs

@brittneypostma made us some very nice icons for the the others :smile:

**Comment by brittneypostma** [comment]
I can do a Reddit one later today.

**Comment by kevmodrome** [comment]
Did you start working on this @brittneypostma ?

**Comment by brittneypostma** [comment]
Oh wow, I had completely forgotten. Thanks for the reminder, I will start right now.

**Comment by kevmodrome** [comment]
Fixed by #83
