### ISSUE TITLE
Umbrella: continuing work on Recipes

### ISSUE THREAD

**Issue by sw-yx** [svelte-society/sveltesociety.dev#8]
we need to pick up with more work from https://github.com/svelte-society/site/pull/7#pullrequestreview-396039175

- implement proper Routify data fetching from markdown https://github.com/sveltech/routify/issues/149
- ??

The rest of the recipes need to be finished, and are being worked on in https://github.com/svelte-society/recipes-mvp

**Comment by kevmodrome** [comment]
Yep! Sounds good. Did you speak with Jake about a good implementation? I'll get cracking on the data structure for the recipes and such.

**Comment by sw-yx** [comment]
not urgent.. i just made this issue for myself. yeah jacob's response is linked in above in the routify link

**Comment by sw-yx** [comment]
not urgent.. i just made this issue for myself. yeah jacob's response is linked in above in the routify link

**Comment by kevmodrome** [comment]
Oh, geez. Totally missed it somehow. Cool!

(removed a duplicate comment as well)

**Comment by Wolfr** [comment]
Why data fetch when you can use mdsvex?

The Routify site has a blog which implements and .svx template with front matter.

https://routify.dev/blog

Repo: https://github.com/sveltech/routify-site-2020

It's a blog but the same logic could be used to write a list of recipes.

**Comment by kevmodrome** [comment]
We're most likely going to use both mdsvex and fetch data. We need to fetch data since we're going to be using a back-end to handle moderation of submissions and writing recipes

**Comment by sw-yx** [comment]
lead the way :) i'll just focus on content.

**Comment by sw-yx** [comment]
i think we transferred the recipes accordingly so we're good here
