### ISSUE TITLE
Move components over from Community to this repo

### ISSUE THREAD

**Issue by kevmodrome** [svelte-society/sveltesociety.dev#81]
We need to move over the components from the old Community site to this one. They can be found here: https://github.com/sveltejs/community/blob/master/data/code.yml

Should be put in a data folder in the root.

Requirments: 
- It should be stored in a JSON format
- Make sure the data lines up with what is in the figma design: https://www.figma.com/file/CWyNLNaQI4yfHULrf1i4UC/Svelte-Society-Website?node-id=172%3A0

**Comment by zygen** [comment]
I can do this (but I don't see a way to grab the issue).

To display the index, you would need `name`, `url`, `tags`, possibly `description` (I'm unsure on that one). `last_updated`, `stars`, and `downloads` are likely to be out of date, and the design doesn't seem to consider them, so they should be dropped?  

If that's correct I'll do that transformation and store in $root/data/components.json

**Comment by zygen** [comment]
Ok, it looks like I was looking at the wrong part of the figma design =)   So, indeed, description, and last_updated are used.  I'm unsure of what the number next to the github logo is for each component, though.  Is that supposed to be stars or downloads?  I'll keep all fields for now and start making that page.

**Comment by zygen** [comment]
I think the data is the right shape now, I just need to figure out how to actually wire it in.

**Comment by zygen** [comment]
PR https://github.com/svelte-society/sveltesociety.dev/pull/83 is getting closer.  Here are the most recent transform commands:

```
ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))' < code.yml > code.json

jq '.resources | map(with_entries(if .key == "name" then .key = "title" else . end)) | map(del(.last_updated, .downloads)) | map(.image = "") | map(.addedOn = (now|strflocaltime("%Y-%m-%dT%H:%M:%SZ"))) | map(.category = "")' code.json > components.json

sed -i.bak -e 's/"`/"/' -e 's/`"/"/' components.json
```

I've got the data in the correct shape and place, and wired up. Remaining things to take care of:

- Tags aren't rendering
- Categories and preview images will have to be populated somehow
- Need a method of keeping this list up to date
- Should the whole card be a link or just the image or just the title?

**Comment by sw-yx** [comment]
do whatever's convenient and we can tweak as we go 👍🏽 


re: Need a method of keeping this list up to date - i think what we do here is make it super clear how to submit a PR to update
