### ISSUE TITLE
Svelte Cheat Sheet

### ISSUE THREAD

**Issue by stephane-vanraes** [svelte-society/sveltesociety.dev#82]
Recently one of the users on Discord shared a Svelte Cheat Sheet (see attachment)

It could be nice to make something similar to put on the Svelte Society site, we can make it nice and printable with

```css
@media print {
 ...
}
```

[SVELTE_-_QUICK_TUTORIAL (1).pdf](https://github.com/svelte-society/sveltesociety.dev/files/5291396/SVELTE_-_QUICK_TUTORIAL.1.pdf)

original version by @Demysdcl

**Comment by sw-yx** [comment]
let's keep this open

**Comment by Isaac-Tait** [comment]
I would like to take a crack at this.

**Comment by sw-yx** [comment]
so the Svelte Brasil folks built this out: https://sveltebrasil.dev/#/cheat

if you have a different vision for how it should look, then be my guest, otherwise i would suggest helping them improve theirs, and then linking from us to them so that it builds global community collaboration

**Comment by Demysdcl** [comment]
Hello, I made this site:
https://sveltebrasil.dev/#/cheat
I can replicate it in your site!

**Comment by HAUDRAUFHAUN** [comment]
maybe this could be a new section just with this windows in it a solution to download it as pdf?

**Comment by Demysdcl** [comment]
https://github.com/svelte-society/sveltesociety.dev/pull/118

**Comment by sw-yx** [comment]
its merged
