### ISSUE TITLE
Is there something like Vuex for Svelte 3?

### ISSUE THREAD

**Issue by frederikhors** [svelte-society/sveltesociety.dev#84]
**Is there something like Vuex for Svelte 3?**

Since I am tired of using GraphQL and want to go back to using classic REST API I would like something to help me in the browser just as the Apollo cache-store has helped me so far.

Especially for persisting in the browser between one session and another of the user.

I opened this: https://stackoverflow.com/questions/64755014/agnostic-data-store-orm-and-caching-layer-for-svelte-3

**Comment by sw-yx** [comment]
why not use svelte stores?

**Comment by frederikhors** [comment]
Yes, that's the idea. But I'm trying to figure out if there is anything more advanced already done.

This is a great article: https://willwillems.com/posts/store-design-in-svelte.html on the subject.

But maybe I can have a look at this too: https://overmindjs.org/views/svelte.

What do you think about?

**Comment by sw-yx** [comment]
no opinion!

**Comment by sw-yx** [comment]
i'm going to say no, theres no vuex for svelte 3 yet. feel free to write one :)
