### ISSUE TITLE
Sveltik suggestion for Form Validation

### ISSUE THREAD

**Issue by websocket98765** [svelte-society/sveltesociety.dev#87]
Great site! 

Wanted to suggest a module for [Form Validation](https://sveltesociety.dev/recipes/component-recipes/form-validation-with-svelte) which produces even cleaner code: [Sveltik](https://github.com/nathancahill/sveltik). It's based on React's [Formik](https://github.com/formium/formik). Very easy to use.

**Comment by websocket98765** [comment]
[svelte-forms-lib](https://github.com/tjinauyeung/svelte-forms-lib) looks _very_ similar and also reasonable.

**Comment by sw-yx** [comment]
cool. we need volunteer dev time to add all these things.

**Comment by websocket98765** [comment]
As an alternative to mini-tutorials, maybe you could just liist a "best" lib name and list others as alternatives. That would add the most value imo & save time, not repeating the 'how to' part found in lib ReadMe's

**Comment by frederikhors** [comment]
"Best" means nothing.

**Comment by antony** [comment]
Agree with @frederikhors - "best" is subjective and disingenuous to other library authors.

**Comment by websocket98765** [comment]
:eye roll: guys  

Would we want or need a diverse ecosystem of svelte/head, svelte/store, svelte/animate libs? No, fortunately we a canonical version of those. 

Now how about frameworks...why do they even exist? To give set of best tools as defined by the creator of the framework. 

The sorting value is what is valuable. 

Otherwise, may as well search Github and each of us individually spend time evaluating every lib to see which is leading lib. That's a waste of time. I thought that was what your website was trying to solve, to help people get going with Svelte.

**Comment by websocket98765** [comment]
Anyway, closing. Please don't get hung up on semantics and lose the point being made.
