### ISSUE TITLE
Need to define the code style rules

### ISSUE THREAD

**Issue by MacFJA** [svelte-society/sveltesociety.dev#89]
I see in the code lots a different code style:
 - Tab vs spaces
 - 2 spaces vs 4 spaces indentation
 - semicolon at end of statement vs no semicolon
 - Script/Template/Style vs Script/Style/Template
 - new line between import and export vs no new line
 - etc.

I think rules should be defined and a CI check should check if they are respected or not.

**Comment by benmccann** [comment]
You could copy the `format` and `lint` commands from SvelteKit:

https://github.com/sveltejs/kit/blob/c0d06c1466952213220e7bffc139cd15ceba1327/packages/kit/package.json#L57

https://github.com/sveltejs/kit/blob/master/.prettierrc

**Comment by kevmodrome** [comment]
I think this definitely makes sense to add. I'd love to have something that runs this when someone opens a PR
