### ISSUE TITLE
Something like this for Svelte?

### ISSUE THREAD

**Issue by frederikhors** [svelte-society/sveltesociety.dev#89]
Do you know if there is something like this for Svelte?

https://swr.vercel.app

**Comment by sw-yx** [comment]
no but doublecheck on the Discord before making it!

**Comment by frederikhors** [comment]
I think those are only a way to block that name. It's the same author and a fake package. We should "report" that to npm. This is not fair behavior.

**Comment by sw-yx** [comment]
yes, npm support is very responsive. if youre interested in doing that just email them.
