### ISSUE TITLE
index svelte community world wide

### ISSUE THREAD

**Issue by sw-yx** [svelte-society/sveltesociety.dev#9]
i think one of our most impt functions will be to help people find their local community, and then helping them grow.

- https://twitter.com/ColombiaSvelte
- https://twitter.com/SveltePortland
- https://twitter.com/SvelteBA
- https://twitter.com/SvelteBangalore
- https://twitter.com/DublinSvelte

etc etc

need to make it ezpz for them to add themselves and discover each other and organize events independently of us

we have communities across 🇳🇱🇩🇰 🇦🇷🇻🇳🇨🇦🇫🇷🇬🇷🇺🇸🇬🇧🇫🇮🇩🇪🇮🇳🇳🇬🇺🇿🇲🇽🇷🇺🇸🇪🇭🇷🇬🇭🇹🇷 🇧🇪🇮🇹🇮🇩🇸🇬🇷🇴🇪🇪🇺🇦🇪🇸🇰🇷🇨🇭🇹🇭🇧🇷🇵🇪🇨🇴🇵🇹🇭🇰

**Comment by kevmodrome** [comment]
Yes, I feel like this is a phase 2 thing, we could probably make something small that just lists something for p1, but after that I am hoping I can do something more dynamic on the backend, unsure how the solution would look like or even what we would want, functionality wise.

**Comment by Wolfr** [comment]
Just as a data point, I tried fixing the Belgium information in the previous version of the site through Netlify CMS and the information never got through.

**Comment by Wolfr** [comment]
A simple static page with a list of meetup groups could already be something, people can always pull request, let's not make it too complicated to begin with?

**Comment by kevmodrome** [comment]
Yep, that's totally fine with me.

**Comment by sw-yx** [comment]
yes, im ready to drop netlifycms and was actually thinking of using google sheets. pr workflow is also fine

**Comment by sw-yx** [comment]
started a twitter list of other svelte societies https://twitter.com/SvelteSociety/status/1256565120051736578?s=20.. aiming to be a partner rather than a blocker

**Comment by tanhauhau** [comment]
How about using airtable？ I can help with that.

**Comment by sw-yx** [comment]
sure

**Comment by sw-yx** [comment]
this is possibly one of the most important functionality still not yet on the site. i should try to work on this.

**Comment by HAUDRAUFHAUN** [comment]
#111 should have implemented it now to the page.

**Comment by sw-yx** [comment]
ok LGTM
