### ISSUE TITLE
Component: Improve new component submission

### ISSUE THREAD

**Issue by MacFJA** [svelte-society/sveltesociety.dev#95]
The number of components doesn't seem to change a lot.

Maybe the process to add a new component is too complicated or bothersome

Should we rethink how components are added ?

----

The current process to to open a PR on the project to edit the [src/pages/components/components.json](https://github.com/svelte-society/sveltesociety.dev/blob/master/src/pages/components/components.json) with all the component information:
```json
{
  "title": "svelte-calendar",
  "url": "https://github.com/6eDesign/svelte-calendar",
  "description": "A lightweight datepicker with neat animations and a unique UX",
  "image": "",
  "npm": "svelte-calendar",
  "stars": 201,
  "tags": [
    "components and libraries",
    "time and date"
  ],
  "image": "",
  "addedOn": "2020-09-29T14:39:13Z",
  "category": "Forms & User Input"
}
```

**Comment by sw-yx** [comment]
agree, i would like to make it easier
