### ISSUE TITLE
Code syntax highlighting lost during migration

### ISSUE THREAD

**Issue by benmccann** [svelte-society/sveltesociety.dev#98]
The page below doesn't have any syntax highlighting or formatting of the code anymore.

https://sveltesociety.dev/recipes/testing-and-debugging/unit-testing-svelte-component/

The syntax highlighting is present in the old repo, but seems to have been lost during the migration https://github.com/svelte-society/sveltesociety.dev-legacy

**Comment by ambarvm** [comment]
Working on this
