### ISSUE TITLE
Cannot GET / error

### ISSUE THREAD

**Issue by Isaac-Tait** [svelte-society/sveltesociety.dev#98]
After forking the repo and running the commands as specified in the README.md doc (`npm install` & `npm run dev:nollup`) when I navigate to localhost:8080 I get the error: **Cannot Get /**

My Firefox Dev Ed tools show three errors:

`404 Not Found`
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”).`
`Content Security Policy: The page’s settings blocked the loading of a resource at http://localhost:8080/favicon.ico (“default-src”).`

and one warning:

`Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://f04972f7-aa78-4e4b-8eac-da112ff16fb4/src/js/editor-popup.js
Source Map URL: purify.js.map`
(Link [here](https://developer.mozilla.org/en-US/docs/Tools/Debugger/Source_map_errors?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default))

To make sure it was not a browser issue I tried in Safari as well and the Dev Tools showed this error:

`Refused to load http://localhost:8080/favicon.ico because it appears in neither the img-src directive nor the default-src directive of the Content Security Policy.`

Everything seems to be load fine on my end. I get the message in my terminal:
[Nollup] Compiled in 2199ms.
[Nollup] Compiled in 31ms.

[Here](https://github.com/Isaac-Tait/sveltesociety.dev) is a link to my fork in case you need a look. I have not done much (yet) except commit the lock file.

**Comment by sw-yx** [comment]
hmm. i can replicate from a fresh install. this seems to be a new regression as i didnt use to have this on my old machine. will check whats going on...

**Comment by silentworks** [comment]
The rollup setup seems fine, its just nollup that has an issue.

**Comment by sw-yx** [comment]
hey @Isaac-Tait, silentworks fixed it :) https://github.com/svelte-society/sveltesociety.dev/pull/101

**Comment by Isaac-Tait** [comment]
The fix is looking good on my end 👍🏼
