### ISSUE TITLE
Typos and improper grammar

### ISSUE THREAD

**Issue by Isaac-Tait** [svelte-society/sveltesociety.dev#99]
I noticed a few grammar issues and typos. I am creating this issue so I can comply with the contribution guidelines. I will submit a PR shortly.

**Comment by Isaac-Tait** [comment]
The contribution guidelines state I should submit my pull request to the `staging` branch. However, I do not see the `staging` branch. Just `addBenchmarkingRecipeStub` and `feature-convert-to-svite`. Is it okay to submit to `master` or am I missing something?

**Comment by peopledrivemecrazy** [comment]
Create a new branch in your repo and make a new PR.
